dist: bionic
sudo: required
language:
  - c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

before_install:
  - sudo apt-get install cppcheck

script:
  # Check versions
  - cppcheck --version
  # Setup standard build
  - cp cfe/cmake/Makefile.sample Makefile
  - cp -r cfe/cmake/sample_defs sample_defs
  # Static code analysis
  #   Below is intent but fails - exit code bug in cppcheck 1.82
  #   - cppcheck --force --inline-suppr --quiet --error-exitcode=1 .
  #   Work around script:
  - cppcheck --force --inline-suppr --quiet . 2> cppcheck_err.txt
  - |
    if [[ -s cppcheck_err.txt ]]; then
      echo "You must fix cppcheck errors before submitting a pull request"
      echo ""
      cat cppcheck_err.txt
      exit -1
    fi

  #cppcheck flight software psp/fsw, osal/src/bsp, osal/src/os, fsw/cfe-core/src
  - cppcheck --force --inline-suppr --std=c99 --language=c --error-exitcode=1 --enable=warning,performance,portability,style --suppress=variableScope --inconclusive psp/fsw osal/src/bsp osal/src/os cfe/fsw/cfe-core/src 2>cppcheck_flighterror.txt
  - |
    if [[ -s cppcheck_flighterror.txt ]]; then
      echo "You must fix cppcheck errors before submitting a pull request"
      echo ""
      cat cppcheck_flighterror.txt
      exit -1
    fi
 
  # Prep and build
  - make prep
  - make
  - make install
  # List cpu1 for core binary
  - ls build/exe/cpu1/
