name: Start QEMU cFS Virtual Machine
description: 'Boots a QEMU virtual machine to execute a CFS build'

inputs:
  binary-dir:
    description: 'Directory containing image files'
    required: true
  exec-image:
    description: 'Docker image name to execute CFS'
    required: false
    default: ghcr.io/core-flight-system/cfsexec-qemu:latest

outputs:
  container-id:
    description: "Docker container ID"
    value: ${{ steps.start-container.outputs.id }}

runs:
  using: 'composite'
  steps:
    - name: Pull CFS container
      shell: bash
      env:
        INPUT_EXEC_IMAGE: ${{ inputs.exec-image }}
      run: docker pull "$INPUT_EXEC_IMAGE"

    - name: Start cFS execution container
      shell: bash
      id: start-container
      env:
        INPUT_BINARY_DIR: ${{ inputs.binary-dir }}
        INPUT_EXEC_IMAGE: ${{ inputs.exec-image }}
      run: |
        DOCKER_ID=$(docker run -d \
          -v "${INPUT_BINARY_DIR}:${INPUT_BINARY_DIR}" \
          --sysctl fs.mqueue.msg_max=64 \
          -w "$INPUT_BINARY_DIR" \
          "$INPUT_EXEC_IMAGE" \
          ./container-start)
        echo "id=$DOCKER_ID" >> $GITHUB_OUTPUT
        echo "Started Container: $DOCKER_ID"
        sleep 2

    - name: List Containers
      shell: bash
      run: docker ps -a