name: Check QEMU cFS Virtual Machine
description: 'Checks boot completion and obtains IP address of virtual machine'

inputs:
  container-id:
    description: "Docker container ID"
    required: true
  healthcheck-regex:
    description: 'String to grep for to identify successful boot'
    required: true
  ssh-keyscan:
    description: 'Whether to execute ssh-keyscan, enable if VM has an SSH server'
    required: false
    default: 'false'

outputs:
  ip-addr:
    description: "Docker container IP address"
    value: ${{ steps.query-ip-addr.outputs.addr }}

runs:
  using: 'composite'
  steps:
    - name: Check for boot completion
      shell: bash
      env:
        INPUT_CONTAINER_ID: ${{ inputs.container-id }}
        INPUT_HEALTHCHECK_REGEX: ${{ inputs.healthcheck-regex }}
      run: |
        count=0
        LOG_FILE="${INPUT_CONTAINER_ID}_logs.txt"
        docker logs "$INPUT_CONTAINER_ID" > "$LOG_FILE"
        while [ $count -lt 30 ] && ! grep -q -- "$INPUT_HEALTHCHECK_REGEX" "$LOG_FILE"
        do
          sleep 2
          count=$(($count+1))
          docker logs "$INPUT_CONTAINER_ID" > "$LOG_FILE"
        done
        echo "Boot log after ${count} iterations:"
        cat "$LOG_FILE"
        grep -q -- "$INPUT_HEALTHCHECK_REGEX" "$LOG_FILE"

    - name: Get IP address of container
      shell: bash
      id: query-ip-addr
      env:
        INPUT_CONTAINER_ID: ${{ inputs.container-id }}
      run: |
        IP_ADDR=$(docker inspect "${INPUT_CONTAINER_ID}" \
          --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}')
        echo "addr=$IP_ADDR" >> $GITHUB_OUTPUT
        echo "Container IP: $IP_ADDR"

    - name: Get SSH key
      if: fromJSON(inputs.ssh-keyscan)
      shell: bash
      env:
        INPUT_CONTAINER_ID: ${{ inputs.container-id }}
      run: |
        mkdir -p ~/.ssh
        chmod 0700 ~/.ssh
        touch ~/.ssh/known_hosts
        chmod 0600 ~/.ssh/known_hosts
        IP_ADDR=$(docker inspect "${INPUT_CONTAINER_ID}" \
          --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}')
        ssh-keyscan -p 2222 "$IP_ADDR" | tee -a ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts