CFS Scheduler (SCH) Application on  User's Guide: sch/fsw/src/sch_custom.h File Reference
sch_custom.h File Reference
#include "cfe.h"
Defines
#define SCH_TIMER_NAME "SCH_MINOR_TIMER"
Functions
int32 SCH_CustomEarlyInit (void)
Custom Early Initialization.
int32 SCH_CustomLateInit (void)
Custom Late Initialization.
uint32 SCH_CustomGetCurrentSlotNumber (void)
Obtains the Current Slot (Minor Frame) number.
void SCH_CustomCleanup (void)
Custom Cleanup.
uint32 SCH_GetMETSlotNumber (void)
Computes a minor slot number from a MET subseconds zero point.
void SCH_MajorFrameCallback (void)
Performs Major Frame Synchronization.
void SCH_MinorFrameCallback (uint32 TimerId)
Performs Minor Frame time step.
Define Documentation
#define SCH_TIMER_NAME "SCH_MINOR_TIMER"
Definition at line 36 of file sch_custom.h.
Referenced by SCH_CustomEarlyInit().
Function Documentation
void SCH_CustomCleanup (void)
Custom Cleanup.
Description
This function is intended to perform any clean up of custom initialization that would be necessary on an application exit
Assumptions, External Events, and Notes:
Any resources that will not be cleaned up automatically be CFE need to be cleaned up in this function.
Definition at line 162 of file sch_custom.c.
References SCH_MajorFrameCallback().
int32 SCH_CustomEarlyInit (void)
Custom Early Initialization.
Description
This function is intended to perform the creation of the minor frame timer. It is called during SCH_TimerInit It may be updated to include other initializations, or modifications to already set scheduler parameters.
Assumptions, External Events, and Notes:
SCH_AppData.ClockAccuracy will be set to the clock resolution in microseconds. CFE_SUCCESS will be returned if all creation was performed properly.
Returns:
CFE_SUCCESS
Return codes from CFE_PSP_TimerInit
Definition at line 66 of file sch_custom.c.
References SCH_MinorFrameCallback(), and SCH_TIMER_NAME.
uint32 SCH_CustomGetCurrentSlotNumber (void)
Obtains the Current Slot (Minor Frame) number.
Description
This function determines the current slot (minor frame) number. It corrects for any minor frame overlap caused by poor minor frame timing, if necessary. This function and associated subfunction was added to the customizable section as on slower platforms this function can have noticible overhead, and several simplifying assumptions can be made on a platform specific basis.
Assumptions, External Events, and Notes:
None
Returns:
Returns slot index from zero to (SCH_TOTAL_SLOTS-1)
Definition at line 123 of file sch_custom.c.
References SCH_GetMETSlotNumber(), SCH_NOT_SYNCHRONIZED, and SCH_TOTAL_SLOTS.
int32 SCH_CustomLateInit (void)
Custom Late Initialization.
Description
This function is intended to perform a wait for startup sync followed by the initialization and starting of the major frame timer, and the starting of the minor frame timer. It may be updated to include other initializations, or modifications to already set scheduler parameters, or remove actions previously performed in SCH_CustomEarlyInit . This function is called following the completion of SCH_AppInit
Assumptions, External Events, and Notes:
Any startup synchronization is included in this function CFE_SUCCESS will be returned if all initialization was performed properly.
Returns:
CFE_SUCCESS
Return codes from CFE_PSP_TimerInit
Definition at line 90 of file sch_custom.c.
References SCH_MajorFrameCallback(), SCH_STARTUP_PERIOD, and SCH_STARTUP_SYNC_TIMEOUT.
uint32 SCH_GetMETSlotNumber (void)
Computes a minor slot number from a MET subseconds zero point.
Description
This function determines the current slot (minor frame) number if one were to assume that slot zero started when the MET microseconds are equal to zero.
Assumptions, External Events, and Notes:
None
Returns:
Returns slot index from zero to (SCH_TOTAL_SLOTS-1)
Definition at line 177 of file sch_custom.c.
References SCH_TOTAL_SLOTS.
Referenced by SCH_CustomGetCurrentSlotNumber(), SCH_MajorFrameCallback(), and SCH_MinorFrameCallback().
void SCH_MajorFrameCallback (void)
Performs Major Frame Synchronization.
Description
This function is called by cFE TIME services when a Major Frame synchronization signal is received. It then synchronizes the minor frame (slot) processing of the Schedule Definition Table.
Assumptions, External Events, and Notes:
None
Definition at line 230 of file sch_custom.c.
References SCH_GetMETSlotNumber(), SCH_MAJOR_FS_CFE_TIME, SCH_MAX_NOISY_MAJORF, SCH_MINOR_SYNCHRONIZED, SCH_NOT_SYNCHRONIZED, and SCH_TOTAL_SLOTS.
Referenced by SCH_CustomCleanup(), and SCH_CustomLateInit().
void SCH_MinorFrameCallback (uint32 TimerId)
Performs Minor Frame time step.
Description
This function is called by an OSAL timer when the minor frame timing reference sends a signal. The Scheduler Application uses this to drive the Application's processing of each minor frame.
Assumptions, External Events, and Notes:
None
Definition at line 349 of file sch_custom.c.
References SCH_GetMETSlotNumber(), SCH_MAJOR_FS_MINOR_FRAME_TIMER, SCH_MAJOR_FS_NONE, SCH_MAJOR_SYNCHRONIZED, SCH_PENDING_MAJOR_SYNCH, and SCH_TOTAL_SLOTS.
Referenced by SCH_CustomEarlyInit().