
# For the native builds, include a wrapper script to start cFS on the container.
if (${SIMULATION} MATCHES "^native")
    install(PROGRAMS ${CMAKE_CURRENT_LIST_DIR}/container-start DESTINATION cpu2)
endif()

set(APP_INCLUDE_TABLE_LIST
    $<TARGET_PROPERTY:ci_lab,INCLUDE_DIRECTORIES>
    $<TARGET_PROPERTY:to_lab,INCLUDE_DIRECTORIES>
    $<TARGET_PROPERTY:sample_app,INCLUDE_DIRECTORIES>
    $<TARGET_PROPERTY:hs,INCLUDE_DIRECTORIES>
    $<TARGET_PROPERTY:cf,INCLUDE_DIRECTORIES>
    $<TARGET_PROPERTY:md,INCLUDE_DIRECTORIES>
    $<TARGET_PROPERTY:mm,INCLUDE_DIRECTORIES>
    $<TARGET_PROPERTY:cs,INCLUDE_DIRECTORIES>
    $<TARGET_PROPERTY:fm,INCLUDE_DIRECTORIES>
    $<TARGET_PROPERTY:lc,INCLUDE_DIRECTORIES>
    $<TARGET_PROPERTY:sc,INCLUDE_DIRECTORIES>
    $<TARGET_PROPERTY:ds,INCLUDE_DIRECTORIES>
    $<TARGET_PROPERTY:hk,INCLUDE_DIRECTORIES>
)

if (NOT CFE_EDS_ENABLED)
    list(APPEND APP_INCLUDE_TABLE_LIST
        $<TARGET_PROPERTY:sbn,INCLUDE_DIRECTORIES>
    )
endif()

# specify extra include dirs for to_lab + sch_lab table builds
target_include_directories(to_lab.table INTERFACE ${APP_INCLUDE_TABLE_LIST})
target_include_directories(sch_lab.table INTERFACE  ${APP_INCLUDE_TABLE_LIST})
