name: Add Issue or PR to Project

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened, ready_for_review, converted_to_draft]

jobs:
  add-to-project:
    name: Add issue or pull request to project
    # do not run on integration candidate branches
    if: ${{ !startsWith(github.head_ref != '' && github.head_ref || github.ref_name, 'ic-') }}
    uses: nasa/cFS/.github/workflows/add-to-project-reusable.yml@dev
    secrets: inherit