name: Static Analysis Reusable Workflow

on:
  workflow_call:
    inputs:
      # Optional inputs
      source-dir:
        description: Directory containing source files
        type: string
        default: 'fsw'

# Force bash to apply pipefail option so pipeline failures aren't masked
defaults:
  run:
    shell: bash

jobs:
  static-analysis:
    name: Run Static Analysis
    runs-on: ubuntu-22.04
    container: ghcr.io/core-flight-system/cfsbuildenv-linux:latest
    timeout-minutes: 15

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          path: source

      - name: Run cppcheck
        uses: nasa/cFS/actions/cppcheck@dev
        id: run-cppcheck
        with:
          source-dir: source/${{ inputs.source-dir }}