name: MCDC Analysis

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  mcdc:
    name: Run MCDC Analysis
    uses: nasa/cFS/.github/workflows/mcdc-reusable.yml@dev